import Head from "next/head";
import getDevelopers from "@/utils/getDevelopers";

import { useEffect, useState } from "react";

import NavList from "@/components/navList";
import ProductForm from "@/components/productForm";
import styles from "../styles/Home.module.css";

export default function addProduct({}){
  const [developers, setDevelopers] = useState()
  
  useEffect(() => {
    if (!developers){
      getDevelopers(setDevelopers)
    }
  })

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavList />
      </header>
      <main>
        <h3>Add Product</h3> 
        { developers && <ProductForm styles={ styles } developers={ developers } setDevelopers ={ setDevelopers }/>}  
      </main>
    </>
  );
}