import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Head from "next/head";
import NavList from "@/components/navList";
import DeveloperList from "@/components/developers/DeveloperList";
import Developer from "@/components/developers/Developer";
import styles from "../styles/Home.module.css";

import getDevelopers from "@/utils/getDevelopers";

export default function Developers({}){
  const router = useRouter();
  const [developer, setDeveloper] = useState();
  const [developers, setDevelopers] = useState();

  useEffect(() => {
    if (!developers && !router.query.name){
      getDevelopers(setDevelopers, {});
    } else if (!developer && router.query.name){
      getDevelopers(setDeveloper, { name: router.query.name });
    }
     if ( !router.query.name && developer ){
       setDeveloper(undefined)
    }
  })

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.nav }>
        <NavList styles={ styles } />
      </header>
      <main className={ styles.main }>
        <h3>{ router.query.name ? 'Developer:' : 'Developers'}</h3>
        { (developers && !developer) && <DeveloperList styles={ styles } developers={ developers } /> }
        { developer && <Developer styles={ styles } developer={ developer }/>}
      </main>
    </>
  );
}