import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Head from "next/head";
import NavList from "@/components/navList";
import TeamList from "@/components/team/TeamList";
import Individual from "@/components/team/Individual";
import styles from "../styles/Home.module.css";

import getDevelopers from "@/utils/getDevelopers";

export default function Developers({}){
  const router = useRouter();
  const name = router.query.name;
  const [developer, setDeveloper] = useState();
  const [developers, setDevelopers] = useState();
 

  useEffect(() => {
    if (!developers && !name){
      getDevelopers(setDevelopers, {});
    } else if ((!developer && name) || (name && developer.name != name)){
      getDevelopers(setDeveloper, { name: name });
    }
     if ( !name && developer ){
       setDeveloper(undefined)
    }
  }, [name, developer, developers, router.query.name])

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.nav }>
        <NavList styles={ styles } />
      </header>
      <main className={ styles.main }>
        <h3>{ router.query.name ? 'Developer:' : 'Developers'}</h3>
        { (developers && !developer) && <TeamList styles={ styles } individuals={ developers } path={ 'developers' }/> }
        { developer && <Individual styles={ styles } individual={ developer }/>}
      </main>
    </>
  );
}