import Head from "next/head";
import getProducts from "@/utils/getProducts";

import { useEffect, useState } from "react";

import NavList from "@/components/navList";
import ProductList from "@/components/products/productList";
import styles from "../styles/Home.module.css";


export default function Products({}){
  const [products, setProducts] = useState()

  useEffect(() => {
    if (!products){
      getProducts(setProducts, {})
    }
  })

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavList />
      </header>
      <main>
        <h3>Products</h3>
        { products && <ProductList styles={ styles } products={ products } setProducts={ setProducts }/> }
      </main>
    </>
  );
}