import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";

import NavList from "@/components/navList";
import ProductForm from "@/components/products/productForm";
import styles from "../styles/Home.module.css";

import getDevelopers from "@/utils/getDevelopers";
import getScrumMasters from "@/utils/getScrumMasters";
import getProducts from "@/utils/getProducts";

export default function addProduct({}){
  const [developers, setDevelopers] = useState()
  const [scrumMasters, setScrumMasters] = useState()
  const [product, setProduct] = useState()
  const router = useRouter();
  
  useEffect(() => {
    if (!developers){
      getDevelopers(setDevelopers, {})
    }

    if (!scrumMasters){
      getScrumMasters(setScrumMasters, {})
    }

    if (router.query.id && !product){
      getProducts(setProduct, { id: router.query.id })
    } 
  })

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.nav }>
        <NavList />
      </header>
      <main>
        <h3>Add Product</h3> 
        { developers && <ProductForm 
          developers={ developers } 
          setDevelopers ={ setDevelopers }
          scrumMasters={ scrumMasters }
          product = { product }
          />}  
      </main>
    </>
  );
}