import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Head from "next/head";
import NavList from "@/components/navList";
import TeamList from "@/components/team/TeamList";
import Individual from "@/components/team/Individual";
import styles from "../styles/Home.module.css";

import getScrumMasters from "@/utils/getScrumMasters";

export default function scrumMasters({}){
  const router = useRouter();
  const { name } = router.query
  const [scrumMaster, setScrumMaster] = useState();
  const [scrumMasters, setScrumMasters] = useState();
 

  useEffect(() => {
    if (!scrumMasters && !name){
      getScrumMasters(setScrumMasters, {});
    } else if (!scrumMaster && name){
      getScrumMasters(setScrumMaster, { name: name });
    }
     if ( !name && scrumMaster ){
       setScrumMaster(undefined)
    }
  }, [name, scrumMaster, scrumMasters])

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.nav }>
        <NavList styles={ styles } />
      </header>
      <main className={ styles.main }>
        <h3>{ router.query.name ? 'Scrum Master:' : 'Scrum Masters:'}</h3>
        { (scrumMasters && !scrumMaster) && <TeamList styles={ styles } individuals={ scrumMasters } path={ 'scrumMasters' }/> }
        { scrumMaster && <Individual styles={ styles } individual={ scrumMaster }/>}
      </main>
    </>
  );
}