# Generated by Django 4.1.7 on 2023-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=50, null=True)),
                ('productOwnerName', models.CharField(blank=True, max_length=50, null=True)),
                ('scrumMasterName', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField(auto_now=True)),
                ('methodology', models.CharField(blank=True, choices=[('AG', 'Agile'), ('WF', 'Waterfall')], max_length=3, null=True)),
            ],
        ),
    ]
