# Generated by Django 4.1.7 on 2023-03-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=50, null=True)),
                ('productOwnerName', models.CharField(blank=True, max_length=50, null=True)),
                ('scrumMasterName', models.CharField(blank=True, max_length=50, null=True)),
                ('methodology', models.CharField(blank=True, max_length=2, null=True)),
                ('developers', models.ManyToManyField(help_text='maximum five developers', to='developers.developer')),
            ],
        ),
    ]
