# Generated by Django 4.1.7 on 2023-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='developers',
            field=models.ManyToManyField(blank=True, null=True, to='users.user'),
        ),
    ]
