import Head from "next/head";
import getProducts from "@/utils/getProducts";
import Link from "next/link";

import { useEffect, useState } from "react";

import NavList from "@/components/navList";
import ProductList from "@/components/products/productList";
import styles from "../../styles/Home.module.css";


export default function Products({}){
  const [products, setProducts] = useState()

  useEffect(() => {
    if (!products){
      getProducts(setProducts, {})
    }
  })

  return (
    <>
      <Head>
        <title>Van Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={ styles.nav }>
        <NavList className={ styles }/>
      </header>
      <main>
        <h3>Products</h3>
        <Link href="/products/productForm"><button>Add New Product</button></Link>
        { products && <>
          <div><h4>Total Number of Products: { products.length }</h4></div>
          <ProductList styles={ styles } products={ products } setProducts={ setProducts }/>
        </>}
      </main>
    </>
  );
}